### ISSUE TITLE
How much should I wait?

### ISSUE THREAD

**Issue by nm17** [mitxela/kicad-round-tracks#12]
My two layer board couldn't finish rounding even after 24 hours. Is this okay?

**Comment by mitxela** [comment]
It usually finishes in a few seconds. If it takes more than a minute it's almost certainly crashed. If you have a very big design, you can try running it on only a selection.

Please can you share your KiCad version info, and also which version of this script you're running (since you mentioned you were running the release script)

See also https://github.com/mitxela/kicad-round-tracks/issues/7 KiCad 6.99 is not supported

**Comment by nm17** [comment]
Okay, thank you!
